name: Update AWS Secret

on:
  workflow_dispatch:
    inputs:
      secret_value:
        description: 'Value to store in AWS Secret'
        required: true
      secret_name:
        description: 'AWS Secret Name'
        required: true

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Boto3
      run: pip install boto3

    - name: Run Boto3 Secret Update Script
      env:
        AWS_REGION: us-east-1
        SECRET_NAME: ${{ github.event.inputs.secret_name }}
        SECRET_VALUE: ${{ github.event.inputs.secret_value }}
      run: python3 update_secret.py
