pipeline{

    agent any

    stages{
        stage('Hello'){
            steps{
                sh '''
                    echo "Hello guys good Morning....!!!
                '''
            }
        }
    }
}