pipeline{
    agent {
        label 'prod'
    }
    stages{
        stage('Git-Chekout'){
            steps{
                git url : 'https://github.com/ManojKRISHNAPPA/test-1.git', branch:'main'
            }
        }
    }
}